cat train_data0.txt > train_all_data.txt
cat train_data1.txt >> train_all_data.txt
cat train_data2.txt >> train_all_data.txt
cat train_data3.txt >> train_all_data.txt
cat train_data4.txt >> train_all_data.txt
cat train_data5.txt >> train_all_data.txt
cat ./v2/train_data0.txt >> train_all_data.txt
cat ./v2/train_data1.txt >> train_all_data.txt
cat ./v2/train_data2.txt >> train_all_data.txt
cat ./v2/train_data3.txt >> train_all_data.txt
cat ./v2/train_data4.txt >> train_all_data.txt
cat ./v2/train_data5.txt >> train_all_data.txt
cat ./v2/train_data6.txt >> train_all_data.txt
